# Site settings
title: Random Markers 
description: Private site for Mano Marks, hacker and developer relations professional
baseurl: ""
url: "http://manomarks.github.io"
twitter_username: ManoMarks 
github_username:  ManoMarks

# Build settings
markdown: kramdown
