# Site settings
title: Random Nodes
description: Private site for Mano Marks, hacker, map fan, and Developer Relations Director at Docker. Views expressed here are my own and not necessarily those of my employer.
baseurl: ""
url: "https://manomarks.net"
enforce_ssl: "https://manomarks.net"
twitter_username: ManoMarks
github_username:  ManoMarks
youtube_playlist: "https://www.youtube.com/watch?v=EReEOMS7gsk&list=PLjoEzhZLEfwdQcPNfQ4EZrcitbs0kQ5JZ"
# Build settings
markdown: kramdown
