# Site settings
title: Random Markers 
description: Private site for Mano Marks, hacker, map fan, and Developer Relations Director at Docker
baseurl: ""
url: "http://manomarks.github.io"
twitter_username: ManoMarks 
github_username:  ManoMarks

# Build settings
markdown: kramdown
